# SPDX-License-Identifier: MIT-0
---
# handlers file for gotify_container_setup

- name: Stop container
  community.docker.docker_container:
    name: "{{ gotifyname_item }}"
    state: "stopped"
  loop:
    - "{{ gotify_container_setup_name }}"
  loop_control:
    loop_var: gotifyname_item